export { default as Calendar } from './calendar.svg?react'
export { default as Camera } from './camera.svg?react'
export { default as ChevronLeft } from './chevron_left.svg?react'
export { default as ChevronRight } from './chevron_right.svg?react'
export { default as Search } from './search.svg?react'
export { default as Setting } from './setting.svg?react'
export { default as User } from './user.svg?react'
